import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Topbutton from "@/components/Topbutton";
import { Toaster } from "@/components/ui/sonner";
import Loader from "@/lib/Loader";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wash Me Car Wash Longview | The Only Handwash Tunnel Around!!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className={inter.className}>
        <Loader>
          {/* <Memberships /> */}
          {/* <Popup /> */}
          <Navbar />
          <Toaster />
          {/* <Script
            src="https://a.omappapi.com/app/js/api.min.js"
            async
            data-user="36493"
            data-account="41469"
          /> */}
          <Script>
      (function (d, u, ac) {
        var s = d.createElement("script");
        s.type = "text/javascript";
        s.src = "https://a.omappapi.com/app/js/api.min.js";
        s.async = true;
        s.dataset.user = u;
        s.dataset.account = ac;
        d.getElementsByTagName("head")[0].appendChild(s);
      })(document, 36493, 41469);
    </Script>

          {children}
          <Topbutton /> <Footer />
        </Loader>
      </body>
    </html>
  );
}
