import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Topbutton from "@/components/Topbutton";
import { Toaster } from "@/components/ui/sonner";
import Loader from "@/lib/Loader";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RouteChangeListener } from "@/provider/RouteChangeListener";
import { OptinMonsterEmbed } from "@/provider/omEmbed";
import Script from "next/script";
import LeadGenForm from "@/components/Popup";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wash Me Car Wash Longview | The Only Handwash Tunnel Around!!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className={inter.className}>
        <Loader>
          <LeadGenForm />
          <Navbar />
          <Toaster />
          <div style={{fontSize: "11px", display: "block", textAlign: "center", fontFamily: "arial", width: "205px"}}>
            <a href="http://www.postcardmania.com/?bid=1130837" target="_blank" rel="noopener noreferrer">
              <img src="//mypostcardmania.com/mailbox/img/0365053m.png" alt="Postcard Advertising" />
            </a>
            <br />
            <a href="http://www.postcardmania.com/?bid=1130837" target="_blank" rel="noopener noreferrer">Postcard Advertising</a>
          </div>
         
          <Script
            type="text/javascript"
            src="https://a.omappapi.com/app/js/api.min.js"
          />
          <RouteChangeListener />
          {children}
          <Topbutton />
          <Footer />
        </Loader>
      </body>
    </html>
  );
}